### PR TITLE
Update gasolene to gasoline

### PR DESCRIPTION
**Pull request by bwignall**
Noticed this via Reddit (https://old.reddit.com/r/pyanodons/comments/1g9wr0c/inconsistent_spelling_for_gasoline_literally/).

Changed all references of "gasolene" to "gasoline" that were found via `git grep -i gasolene` (excluding the changelog).

### CODE REVIEW

**Comment by notnotmelon** [comment]
Please provide a migration `.json` file and update the changelog.

**Comment by bwignall** [comment]
I have attempted to add a migration file, following https://github.com/pyanodon/pyindustry/blob/master/migrations/1.0.7.json . Please let me know if I need to change it.

**Comment by notnotmelon** [comment]
The JSON migration is incorrect. I do not have write access to your branch. Here is the corrected migration:

```
{
  "equipment": [
    [
      "portable-gasolene-generator",
      "portable-gasoline-generator"
    ]
  ],
  "item": [
    [
      "portable-gasolene-generator",
      "portable-gasoline-generator"
    ]
  ],
  "recipe": [
    [
      "portable-gasolene-generator",
      "portable-gasoline-generator"
    ]
  ]
}
```

**Comment by bwignall** [comment]
Thank you for your help and your patience. I have updated the JSON migration to what you gave.

**Pull request merged**
