### PR TITLE
Fluid void recipes fix?

### PR DESCRIPTION
**Pull request by Fabboz**

### CODE REVIEW

**Comment by Nexela** [comment]
Not sure What this is trying to accomplish, some fluids can be both a liquid and a gas, So a vent recipe is needed for both.

**Comment by Fabboz** [comment]
fluid like copper pulp got a gas temperature of 15. It can't be vented but i think create a duplicate , not working venting recipe. Maybe all goes to PyVoid subgroup?

**Comment by Fabboz** [comment]
methanol is the same.

**Comment by Fabboz** [comment]
also check here how i fixed icons:
https://github.com/Fabboz/pyindustry/tree/Fluid/Gas-voiding-fix

**Comment by Fabboz** [comment]
sorry here:
https://github.com/Fabboz/pyindustry/commit/dd79891ccd7d2ee75402c58d9ef47e06d850f77e

**Comment by Fabboz** [comment]
and here:
https://github.com/Fabboz/pycoalprocessing/commit/e59af80fe4f7e818acdf025e38940d619936285c

**Pull request merged**
