### PR TITLE
Fixed Coal and Asphalt tile names

### PR DESCRIPTION
**Pull request by JStMorgan**
This PR fixes a locale issue I left behind in #90 , and also adds the change to vanilla paving tiles to the changelog.

### CODE REVIEW

**Comment by notnotmelon** [comment]
Both spellings of gasolene are valid. I think it should stay as-is.

image

**Comment by JStMorgan** [comment]
Well, I learned something today! Have reverted that change.

I've encountered a related issue - in my current map, my previously-placed Asphalt and Coal tiles have reverted back to being Lab tiles, along with the desired changes to dev environments. Would it be possible to construct a migration script so people's saves aren't impacted by this? Hoping you can advise ⚙️

**Comment by notnotmelon** [comment]
put this under the migrations folder

```{
    "tile": [
        ["lab-dark-1", "py-coal-tile"],
        ["lab-dark-2", "py-asphalt"]
    ]
}```

**Comment by JStMorgan** [comment]
Have just tested the fix and it worked, both in an existing game and in a lab environment! The only thing not to be affected were the menu simulations, which still use the lab tiles.

**Comment by notnotmelon** [comment]
Merged! Thank you

**Pull request merged**
